# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KO1Emw53NoySjnfI5AAsI8rXKJ_ePgRl
"""

pip install googletrans==4.0.0-rc1

from googletrans import Translator


textfromuser = input("Enter the text to translate: ")
target_lang= input("Enter the target language code (e.g., 'en' for English, 'es' for Spanish,'ur' for urdu, 'hi' for hindi, 'ms' for Malay): ")

translator = Translator()

translatedtext = translator.translate(textfromuser, dest=target_lang).text

print(f"Translated Text: {translatedtext}")